# Generated by Django 3.1 on 2020-08-19 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='article',
            name='updated_at',
        ),
    ]
